server:
  port: 8001


spring:
  #配置
  profiles:
    active: test
  application:
    #服务在注册中心的名称
    name: alibaba-service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.82:8848

#    nacos:
#      discovery:
#        #Nacos服务注册中心地址
#        server-addr: 192.168.2.82:8848
#    sentinel:
#      transport:
#        #配置Sentin dashboard地址
#        dashboard: 192.168.2.82:8080
#        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
#        port: 8719
#      datasource:
#        ds1:
#          nacos:
#            server-addr: 192.168.2.82:8848
#            dataId: cloudalibaba-sentinel-service
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true #激活Sentinel 对Feign的支持

#mybatis
mybatis:
  #指定mapper文件扫描位置
  mapper-locations: classpath:mapper/*Mapper.xml